
server:
  port: 8081

spring:
  application:
    name: ingestion-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

fleet:
  kafka:
    topic: telemetry.events.v1
  security:
    shared-secret: "change-me-in-production-hmac-secret-key"
